config/routes.rb
Rails.application.routes.draw do
  get '/projects', to: 'projects#index'
  get '/projects/new', to: 'projects#new'
  get '/projects/:id', to: 'projects#show', as: 'project'
  # get '/projects/:id', to: 'projects#show'
  # post '/projects', to: 'projects#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :read_projects

  def index
    #show all of the resources
  end
  def new
    #to have a form that allows you to create a new resource
  end
  def show
    #show one of the resources
    @project = @projects.find do |project|
      project[:id] == params[:id].to_i
    end
  end

  private

  def read_projects
    @projects = [
      {
        id: 1,
        name: 'terminal app',
        github_status: true,
        date_completed: '17/08/2020'
      },
      {
        id: 2,
        name: 'react app',
        github_status: false,
        date_completed: '20/10/2020'
      }
    ]
  end
  # def create
  # end
end


# class ProjectsController < ApplicationController
#   before_action :read_projects
#   skip_before_action :verify_authenticity_token
  
#   def index
#     # send back all of the resources to the client
#     render json: @projects
#   end

#   def show
#     # show is for sending back only one resource
#     found_project = @projects.find do |project|
#       project["id"] == params[:id].to_i
#     end

#     render json: found_project
#   end

#   def create
#     new_project = {
#       id: params[:id].to_i, 
#       name: params[:name], 
#       github_status: is_true?(params[:github_status])}
#     @projects << new_project
#     write_projects(@projects)
#     redirect_to projects_path
#   end

#   private

#   def is_true?(bool)
#     bool == true
#   end

#   def write_projects(projects)
#     File.write(Rails.public_path.join("projects.json"), JSON.generate(projects))
#   end

#   def read_projects
#     @projects = JSON.parse(File.read(Rails.public_path.join("projects.json")))
#   end

# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagementApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/projects/_card.html.erb
<li class="card">
  <%= link_to project[:name], project_path(project[:id]) %>
  <ul>
    <li>
      github status: <%= project[:github_status] ? "👍" : "👎" %>
    </li>
    <li>
      data completed: <%= project[:date_completed] %>
    </li>
  </ul>
</li>

app/views/projects/index.html.erb
<h1>Projects</h1>
<h2>Projects list</h2>

<%= image_tag asset_path('dog.jpg'), width: 400 %>

<ul>
  <% @projects.each do |project| %>
    <%= render partial: 'card', locals: { project: project } %>
  <% end %>
</ul>

<%= @projects %>

app/views/projects/new.html.erb
<h1>On new page</h1>

app/views/projects/show.html.erb
<h1>Project</h1>

<ul>
  <li>
    <%= link_to @project[:name], project_path(@project[:id]) %>
    <ul>
      <li>
        github status: <%= @project[:github_status] ? "👍" : "👎" %>
      </li>
      <li>
        data completed: <%= @project[:date_completed] %>
      </li>
    </ul>
  </li>
</ul>

app/views/shared/_nav.html.erb
<nav>
  <%= link_to "Projects", projects_path %>
  <%= link_to "New Project Page", projects_new_path %>
</nav>